### ISSUE TITLE
Make the circle underneath the cursor different colors

### ISSUE THREAD

**Issue by mkirsch42** [AmityHighCSDevTeam/Onslaught#5]
It should be a different color for when your gun is reloading, cooling down, and ready to fire.

**Comment by SergeySave** [comment]
Cooling down and reloading are both currently yellow.   
Ready to fire is currently clear.   
I can change reloading to a different color.

**Comment by mkirsch42** [comment]
Ready to fire is not clear. It's red until you buy a gun and buy ammo; after that it is always yellow.

**Comment by SergeySave** [comment]
Nvm it is yellow when less than 1 magazine of ammo. It is red when out of ammo.

**Comment by SergeySave** [comment]
New status indicator colors:  
- Clear: Can fire and > 1 mag of ammo
- Yellow: Can fire and < 1 mag of ammo
- Blue: Cannot fire and > 1 mag of ammo
- Green: Cannot fire and < 1 mag of ammo
- Red: Out of ammo (Cannot fire)
